name: Monthly cron

on:
  # schedule:
  #   # run every 20th of the month at 6am UTC
  #   - cron: '0 6 20 * *'
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:

jobs:
  test_more_architectures:

    # The following architectures are emulated and are therefore slow, so
    # we include them just in the weekly cron. These also serve as a test
    # of using system libraries and using pytest directly.

    name: Python 3.7 on ${{ matrix.arch }}
    if: startsWith(github.repository, 'mhvk')
    runs-on: ubuntu-20.04
    env:
      apt_packages: |
        python3-astropy
        python3-pyfftw
        python3-h5py
        python3-yaml
        python3-pip

    strategy:
      fail-fast: false
      matrix:
        include:
          # - arch: aarch64
          # - arch: ppc64le
          - arch: s390x

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run tests
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: testing
          shell: /bin/bash
          install: |
            apt-get update -q -y
            apt-get install -y ${{ env.apt_packages }}
          run: |
            python3 -m pip install --user baseband
            python3 setup.py egg_info
            pytest-3

  test_with_apt:
    name: Test using apt
    runs-on: ubuntu-20.04
    if: startsWith(github.repository, 'mhvk')
    strategy:
      fail-fast: false
      matrix:
        include:

          - name:
            apt_packages: |
              python3-astropy
              python3-pyfftw
              python3-h5py
              python3-yaml
              python3-pip
            pip_packages: baseband

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install system dependencies
      if: matrix.apt_packages
      run: sudo apt-get install ${{ matrix.apt_packages }}
    - name: Install Python dependencies
      run: python -m pip install --user ${{ matrix.pip_packages }}
    - name: Run tests
      run: |
        python3 setup.py egg_info
        pytest-3

  test_other_os:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: startsWith(github.repository, 'mhvk')
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Test with apt
            os: windows-latest
            python: 3.8
            toxenv: py38-test

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox ${{ matrix.pip_packages }}
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
